### ISSUE TITLE
Misc improvements

### ISSUE THREAD

**Issue by VitorTrin** [joao2391/elixiagenciasbancos#1]
- In elixir, we use pascal case for modules, so this module should be named ElixirAgenciasBancos

https://github.com/joao2391/elixiagenciasbancos/blob/90abd1e397f608de147094a4e93c5ab43105f8e5/lib/elixagenciasbancos.ex#L1

- It's a better pratice to use logs instead of  `IO.inspect` in production code, so this would be better as `Logger.error(inspect(reason))

https://github.com/joao2391/elixiagenciasbancos/blob/90abd1e397f608de147094a4e93c5ab43105f8e5/lib/elixagenciasbancos.ex#L18

- mix format is the official language linter, it's a good idea to use it

- The `{code, raw_body}` part does nothing, it's not being assigned to a variable and isn't used in a function, its like you had a random string in the middle of the code

https://github.com/joao2391/elixiagenciasbancos/blob/90abd1e397f608de147094a4e93c5ab43105f8e5/lib/elixagenciasbancos.ex#L31

**Comment by joao2391** [comment]
Thank you for point those mistakes. I've started to learn Elixir a few months ago.
So the last one I didn't get it. What do you suggest to change?

**Comment by VitorTrin** [comment]
Instead of
```elixir
  {:ok, %{body: raw_body, status_code: code}} -> {code, raw_body}
      retorno = Jason.decode!(raw_body)
```

you could do

```elixir
  {:ok, %{body: raw_body, status_code: code}} ->
      retorno = Jason.decode!(raw_body)
```

I recommend installing credo, it's an analysis tool focused in learning, it points out for you this kinds of mistakes
https://hex.pm/packages/credo

**Comment by joao2391** [comment]
I'll fix that. Thank you very much!
